from __future__ import annotations

BLOCKS = {
    1: {
        "name": "Правовые основы",
        "icon": "📜",
        "description": "Законы, документы, сроки, ответственность.",
    },
    2: {
        "name": "Оружие и безопасность",
        "icon": "🔫",
        "description": "Хранение, транспортировка, техника безопасности.",
    },
    3: {
        "name": "Биология и практика охоты",
        "icon": "🦌",
        "description": "Виды животных, этика, угодья, сезонность.",
    },
}

DEFAULT_SETTINGS = {
    "questions_per_session": 20,
    "timer_seconds": 0,
    "show_explanations": True,
}

FREE_LIMITS = {
    "trail_per_block": 30,
    "trainings": 5,
}

PREMIUM_PRICES = {
    "rub": 490,
    "stars": 350,
}

RANKS = [
    {
        "code": "egg",
        "name": "Птенец",
        "icon": "🥚",
        "min_correct": 0,
        "quote": "",
    },
    {
        "code": "tracker",
        "name": "Следопыт",
        "icon": "🐣",
        "min_correct": 30,
        "quote": "Следопыт видит то, что другие не замечают.",
    },
    {
        "code": "beater",
        "name": "Загонщик",
        "icon": "🦊",
        "min_correct": 70,
        "quote": "Загонщик знает лес, но впереди самое интересное.",
    },
    {
        "code": "shooter",
        "name": "Стрелок",
        "icon": "🐺",
        "min_correct": 120,
        "quote": "Стрелок не промахивается дважды в одну цель.",
    },
    {
        "code": "gamekeeper",
        "name": "Егерь",
        "icon": "🦅",
        "min_correct": 180,
        "quote": "Егерь знает каждую тропу. Вы почти у цели.",
    },
    {
        "code": "hunter",
        "name": "Охотник",
        "icon": "🏆",
        "min_correct": 230,
        "quote": "Охотник знает, куда и зачем идти.",
    },
    {
        "code": "master",
        "name": "Мастер-охотник",
        "icon": "👑",
        "min_correct": 257,
        "quote": "Вы прошли все 257 вопросов. Теперь вы готовы к настоящей охоте.",
    },
]

XP_LEVELS = [
    (1, 0, "Новобранец"),
    (2, 50, ""),
    (3, 120, ""),
    (4, 210, ""),
    (5, 320, ""),
    (6, 500, ""),
    (7, 700, ""),
    (8, 950, ""),
    (9, 1250, ""),
    (10, 1600, ""),
    (11, 2000, ""),
    (12, 2500, ""),
    (13, 3100, ""),
    (14, 3800, ""),
    (15, 4600, ""),
    (16, 5500, ""),
    (17, 6500, ""),
    (18, 7600, ""),
    (19, 8800, ""),
    (20, 10000, "Ветеран"),
    (21, 12000, ""),
    (22, 14000, ""),
    (23, 16500, ""),
    (24, 19000, ""),
    (25, 22000, "Легенда"),
]

XP_RULES = {
    "trail_correct": 5,
    "training_correct": 8,
    "first_time_correct": 12,
    "fast_correct": 15,
    "exam_correct": 10,
    "mistake_fixed": 10,
    "repetition_correct": 3,
    "daily_question_correct": 20,
    "blitz_correct": 16,
    "streak_5": 10,
    "streak_10": 25,
    "streak_20": 50,
    "streak_50": 150,
    "block_completed": 100,
    "progress_25": 50,
    "progress_50": 100,
    "progress_75": 150,
    "progress_100": 500,
    "exam_completed": 50,
    "exam_pass_75": 300,
    "exam_pass_80": 500,
    "exam_pass_90": 1000,
    "day_streak_3": 30,
    "day_streak_7": 200,
    "day_streak_14": 500,
    "day_streak_30": 1500,
    "daily_task": 100,
    "duel_win": 50,
    "duel_loss": 20,
    "challenge_completed": 30,
}

COIN_RULES = {
    "correct": 1,
    "day_streak_3": 10,
    "day_streak_7": 30,
    "day_streak_14": 75,
    "day_streak_30": 200,
    "new_rank": 50,
    "exam_passed": 100,
    "achievement": 20,
    "duel_win": 10,
    "challenge_completed": 5,
    "daily_question_correct": 2,
}

HINT_COSTS = {
    "50_50": 5,
    "keyword": 4,
    "source": 2,
    "plus_30": 3,
}

ROUTE_TASKS = {
    1: {"icon": "🗺", "name": "Тропа Права (ч.1)", "minutes": 15, "goal": "Вопросы 1-49", "callback": "trail_block_1", "mode": "trail"},
    2: {"icon": "🗺", "name": "Тропа Права (ч.2)", "minutes": 15, "goal": "Вопросы 50-98", "callback": "trail_block_1", "mode": "trail"},
    3: {"icon": "🗺", "name": "Тропа Безопасности", "minutes": 15, "goal": "Вопросы 1-74", "callback": "trail_block_2", "mode": "trail"},
    4: {"icon": "🗺", "name": "Тропа Природы (ч.1)", "minutes": 15, "goal": "Вопросы 1-42", "callback": "trail_block_3", "mode": "trail"},
    5: {"icon": "🗺", "name": "Тропа Природы (ч.2)", "minutes": 15, "goal": "Вопросы 43-85", "callback": "trail_block_3", "mode": "trail"},
    6: {"icon": "🎯", "name": "Стрельбище — все тропы", "minutes": 12, "goal": "20 вопросов, 65%+", "callback": "training", "mode": "training"},
    7: {"icon": "🎯", "name": "Стрельбище — слабые", "minutes": 12, "goal": "20 вопросов, 70%+", "callback": "training_weak", "mode": "training"},
    8: {"icon": "🔄", "name": "Разбор промахов", "minutes": 15, "goal": "Исправить 80%", "callback": "mistakes", "mode": "mistakes"},
    9: {"icon": "🎯", "name": "Стрельбище с таймером", "minutes": 12, "goal": "20 вопросов с таймером 60с, 70%+", "callback": "training_timed", "mode": "training"},
    10: {"icon": "⚡", "name": "Блиц-стрельбище", "minutes": 10, "goal": "20 вопросов, 75%+", "callback": "blitz", "mode": "blitz"},
    11: {"icon": "📝", "name": "Испытание #1", "minutes": 60, "goal": "75%+", "callback": "exam", "mode": "exam"},
    12: {"icon": "🔄", "name": "Разбор промахов Испытания", "minutes": 20, "goal": "Исправить 80%", "callback": "mistakes", "mode": "mistakes"},
    13: {"icon": "📝", "name": "Испытание #2", "minutes": 60, "goal": "80%+", "callback": "exam", "mode": "exam"},
    14: {"icon": "🎯", "name": "Лёгкая разминка + отдых", "minutes": 10, "goal": "Расслабьтесь!", "callback": "training", "mode": "training"},
}

DAILY_CHALLENGES = {
    0: {"type": "streak_5", "name": "Серия пять", "icon": "🔥", "description": "Сделайте 5 правильных ответов подряд.", "xp": 30, "coins": 5},
    1: {"type": "blitz_10", "name": "Блиц-10", "icon": "⚡", "description": "Пройдите блиц и наберите 10 правильных.", "xp": 40, "coins": 8},
    2: {"type": "fix_5", "name": "Промахобой", "icon": "🔄", "description": "Исправьте 5 ошибок сегодня.", "xp": 35, "coins": 5},
    3: {"type": "starred_3", "name": "Трудные следы", "icon": "⭐", "description": "Пройдите 3 избранных вопроса.", "xp": 30, "coins": 5},
    4: {"type": "duel", "name": "Дуэль", "icon": "⚔️", "description": "Победите Михалыча в дуэли.", "xp": 50, "coins": 10},
    5: {"type": "marathon_30", "name": "Марафон", "icon": "🏃", "description": "Ответьте на 30 вопросов за день.", "xp": 60, "coins": 15},
    6: {"type": "easy_1", "name": "Отдых", "icon": "🦆", "description": "Ответьте хотя бы на один вопрос дня.", "xp": 20, "coins": 3},
}

ACHIEVEMENTS = [
    {"code": "first_shot", "name": "Первый выстрел", "category": "first_steps", "description": "Ответьте на первый вопрос", "metric": "total_answers", "target": 1, "xp": 10, "coins": 5, "secret": False},
    {"code": "three_in_row", "name": "Три в ряд", "category": "first_steps", "description": "3 правильных подряд", "metric": "max_streak", "target": 3, "xp": 20, "coins": 5, "secret": False},
    {"code": "ten_streak", "name": "Десяточка", "category": "first_steps", "description": "10 правильных подряд", "metric": "max_streak", "target": 10, "xp": 50, "coins": 10, "secret": False},
    {"code": "no_miss_20", "name": "Без промаха", "category": "first_steps", "description": "20 без ошибок подряд", "metric": "max_streak", "target": 20, "xp": 100, "coins": 20, "secret": False},
    {"code": "doublet", "name": "Дуплет", "category": "first_steps", "description": "2 блока за один день", "metric": "blocks_today", "target": 2, "xp": 50, "coins": 10, "secret": False},
    {"code": "rank_tracker", "name": "Следопыт", "category": "progress", "description": "Звание Следопыт", "metric": "correct_total", "target": 30, "xp": 30, "coins": 10, "secret": False},
    {"code": "halfway", "name": "Полпути", "category": "progress", "description": "128 вопросов пройдено", "metric": "questions_completed", "target": 128, "xp": 100, "coins": 20, "secret": False},
    {"code": "marathon", "name": "Марафонец", "category": "progress", "description": "Все 257 вопросов", "metric": "questions_completed", "target": 257, "xp": 500, "coins": 100, "secret": False},
    {"code": "patient", "name": "Терпеливый", "category": "progress", "description": "7 дней подряд", "metric": "day_streak", "target": 7, "xp": 200, "coins": 30, "secret": False},
    {"code": "speedster", "name": "Скорострел", "category": "progress", "description": "10 ответов быстрее 10 секунд", "metric": "fast_answers", "target": 10, "xp": 100, "coins": 20, "secret": False},
    {"code": "lawyer", "name": "Юрист", "category": "mastery", "description": "100% в блоке 1", "metric": "block1_percent", "target": 100, "xp": 300, "coins": 50, "secret": False},
    {"code": "safety_expert", "name": "Безопасник", "category": "mastery", "description": "100% в блоке 2", "metric": "block2_percent", "target": 100, "xp": 300, "coins": 50, "secret": False},
    {"code": "biologist", "name": "Биолог", "category": "mastery", "description": "100% в блоке 3", "metric": "block3_percent", "target": 100, "xp": 300, "coins": 50, "secret": False},
    {"code": "encyclopedist", "name": "Энциклопедист", "category": "mastery", "description": "100% во всех блоках", "metric": "all_blocks", "target": 100, "xp": 1000, "coins": 200, "secret": False},
    {"code": "winner", "name": "Победитель", "category": "mastery", "description": "Сдать испытание с первой попытки", "metric": "exam_first_pass", "target": 1, "xp": 500, "coins": 100, "secret": False},
    {"code": "week_hunter", "name": "Неделя охотника", "category": "streak", "description": "7 дней подряд", "metric": "day_streak", "target": 7, "xp": 200, "coins": 30, "secret": False},
    {"code": "two_week_march", "name": "Двухнедельный марш", "category": "streak", "description": "14 дней подряд", "metric": "day_streak", "target": 14, "xp": 500, "coins": 75, "secret": False},
    {"code": "iron_will", "name": "Железная воля", "category": "streak", "description": "30 дней подряд", "metric": "day_streak", "target": 30, "xp": 1500, "coins": 200, "secret": False},
    {"code": "lightning", "name": "Молния", "category": "speed", "description": "Испытание за 45 минут", "metric": "exam_time", "target": 45, "xp": 300, "coins": 50, "secret": False, "comparison": "lte"},
    {"code": "express", "name": "Экспресс", "category": "speed", "description": "20 вопросов тренировки за 5 минут", "metric": "training_time", "target": 5, "xp": 200, "coins": 30, "secret": False, "comparison": "lte"},
    {"code": "self_work", "name": "Работа над собой", "category": "fix", "description": "50 ошибок исправлено", "metric": "mistakes_fixed", "target": 50, "xp": 200, "coins": 30, "secret": False},
    {"code": "phoenix", "name": "Феникс", "category": "fix", "description": "Провалить, а потом сдать испытание", "metric": "failed_then_passed", "target": 1, "xp": 500, "coins": 100, "secret": False},
    {"code": "persistent", "name": "Упорный", "category": "fix", "description": "Три раза довести тему до 100%", "metric": "topic_mastered_3x", "target": 1, "xp": 200, "coins": 30, "secret": False},
    {"code": "challenger", "name": "Вызов принят", "category": "challenge", "description": "14 вызовов подряд", "metric": "challenges_streak", "target": 14, "xp": 300, "coins": 50, "secret": False},
    {"code": "duel_master", "name": "Мастер дуэлей", "category": "duel", "description": "5 побед в дуэлях", "metric": "duel_wins", "target": 5, "xp": 200, "coins": 30, "secret": False},
    {"code": "card_collector", "name": "Коллекционер", "category": "cards", "description": "50 карточек изучено", "metric": "cards_viewed", "target": 50, "xp": 200, "coins": 30, "secret": False},
    {"code": "full_collection", "name": "Полная коллекция", "category": "cards", "description": "Все карточки изучены", "metric": "cards_viewed", "target": 73, "xp": 300, "coins": 50, "secret": False},
    {"code": "night_owl", "name": "Полуночник", "category": "secret", "description": "Заниматься после 23:00", "metric": "studied_after_23", "target": 1, "xp": 50, "coins": 10, "secret": True},
    {"code": "early_bird", "name": "Ранняя пташка", "category": "secret", "description": "Заниматься до 6:00", "metric": "studied_before_6", "target": 1, "xp": 50, "coins": 10, "secret": True},
    {"code": "perfect_257", "name": "257", "category": "secret", "description": "Все 257 ответов правильные", "metric": "correct_total", "target": 257, "xp": 2000, "coins": 500, "secret": True},
]

ANIMAL_CARDS = [
    {
        "name": "Лось",
        "latin_name": "Alces alces",
        "category": "Копытные",
        "order_name": "Парнокопытные",
        "family_name": "Оленевые",
        "weight": "200-600 кг",
        "body_length": "2.4-3.1 м",
        "lifespan": "15-20 лет",
        "habitat": "Леса, болотистые районы, тайга.",
        "hunting_season": "По региональным правилам и лимитам добычи.",
        "special_rules": "Требуются разрешение и соблюдение лимитов.",
        "track_description": "Крупный вытянутый след с выраженными копытами.",
        "image_url": "",
        "track_image_url": "",
        "question_ids": [73, 240, 287],
    },
    {
        "name": "Кабан",
        "latin_name": "Sus scrofa",
        "category": "Копытные",
        "order_name": "Парнокопытные",
        "family_name": "Свиньи",
        "weight": "60-250 кг",
        "body_length": "1.2-1.8 м",
        "lifespan": "10-14 лет",
        "habitat": "Смешанные леса, камыши, овраги.",
        "hunting_season": "По общим срокам и региональным ограничениям.",
        "special_rules": "Часто активен в сумерках и ночью.",
        "track_description": "Округлый след копыт, шире и короче, чем у оленевых.",
        "image_url": "",
        "track_image_url": "",
        "question_ids": [221, 271],
    },
    {
        "name": "Заяц-беляк",
        "latin_name": "Lepus timidus",
        "category": "Пушные",
        "order_name": "Зайцеобразные",
        "family_name": "Зайцевые",
        "weight": "2-5 кг",
        "body_length": "45-65 см",
        "lifespan": "5-8 лет",
        "habitat": "Леса, кустарники, опушки.",
        "hunting_season": "Обычно осень-зима в установленные сроки.",
        "special_rules": "Зимой меняет окраску на белую.",
        "track_description": "Характерные парные прыжковые следы с длинными задними лапами.",
        "image_url": "",
        "track_image_url": "",
        "question_ids": [279, 262],
    },
    {
        "name": "Бурый медведь",
        "latin_name": "Ursus arctos",
        "category": "Хищники",
        "order_name": "Хищные",
        "family_name": "Медвежьи",
        "weight": "100-600 кг",
        "body_length": "1.7-2.8 м",
        "lifespan": "20-30 лет",
        "habitat": "Тайга, горные леса, тундровые окраины.",
        "hunting_season": "Строго по разрешениям и региональным срокам.",
        "special_rules": "Опасный зверь, требуется особая осторожность.",
        "track_description": "Широкий след с отпечатками пяти пальцев и когтей.",
        "image_url": "",
        "track_image_url": "",
        "question_ids": [240],
    },
    {
        "name": "Волк",
        "latin_name": "Canis lupus",
        "category": "Хищники",
        "order_name": "Хищные",
        "family_name": "Псовые",
        "weight": "30-60 кг",
        "body_length": "1.0-1.6 м",
        "lifespan": "8-12 лет",
        "habitat": "Леса, степи, лесотундра.",
        "hunting_season": "По региональным правилам регулирования численности.",
        "special_rules": "Часто перемещается стаями.",
        "track_description": "Похож на крупную собаку, но более вытянутый и собранный след.",
        "image_url": "",
        "track_image_url": "",
        "question_ids": [266, 270, 275],
    },
    {
        "name": "Утка-кряква",
        "latin_name": "Anas platyrhynchos",
        "category": "Водоплавающая дичь",
        "order_name": "Гусеобразные",
        "family_name": "Утиные",
        "weight": "0.8-1.5 кг",
        "body_length": "50-65 см",
        "lifespan": "5-10 лет",
        "habitat": "Реки, озёра, болота, старицы.",
        "hunting_season": "Летне-осенняя охота по срокам региона.",
        "special_rules": "Одна из самых распространённых охотничьих уток.",
        "track_description": "На суше заметны перепончатые лапы с тремя передними пальцами.",
        "image_url": "",
        "track_image_url": "",
        "question_ids": [218, 263],
    },
    {
        "name": "Вальдшнеп",
        "latin_name": "Scolopax rusticola",
        "category": "Боровая дичь",
        "order_name": "Ржанкообразные",
        "family_name": "Бекасовые",
        "weight": "250-450 г",
        "body_length": "33-38 см",
        "lifespan": "8-10 лет",
        "habitat": "Сырые леса и перелески.",
        "hunting_season": "Весенняя тяга и осенние сроки по правилам региона.",
        "special_rules": "Известен брачным полётом — тягой.",
        "track_description": "Небольшие птичьи следы в сырой почве и на песке.",
        "image_url": "",
        "track_image_url": "",
        "question_ids": [258, 296],
    },
    {
        "name": "Тетерев",
        "latin_name": "Lyrurus tetrix",
        "category": "Боровая дичь",
        "order_name": "Курообразные",
        "family_name": "Фазановые",
        "weight": "0.9-1.8 кг",
        "body_length": "40-58 см",
        "lifespan": "6-9 лет",
        "habitat": "Опушки, болота, редколесье, луга.",
        "hunting_season": "По сезонным срокам для боровой дичи.",
        "special_rules": "Весной токует на открытых местах.",
        "track_description": "Трёхпалые следы куриной формы, заметны на снегу и грунте.",
        "image_url": "",
        "track_image_url": "",
        "question_ids": [257],
    },
]

QUOTES = [
    "Лучший день вернуться на тропу — сегодня.",
    "Даже один вопрос в день приближает к охотничьему билету.",
    "Точность приходит к тем, кто не бросает практику.",
    "Сильный охотник сперва изучает правила, а потом берёт ружьё.",
    "Серия держится на одном маленьком шаге сегодня.",
]
